name: Update FM4 Podcast Feed

on:
  schedule:
    # Run once every day at 08:00 UTC
    - cron: "0 8 * * *"

  # Also allow us to run it manually.
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Generate FM4 podcast feed
        run: |
          python generate_feed.py

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload feed
        uses: actions/upload-pages-artifact@v3
        with:
          path: "."

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
